CREATE TABLE DEVELOPERS (
IMP_ID NUMBER PRIMARY KEY,
forname VARCHAR2(20),
surname VARCHAR2(20) NOT NULL,
dateOfEmp DATE NOT NULL,
posInProject VARCHAR2(20),
CONSTRAINT CHECK_CORRECT_DATE CHECK 
(dateOfEmp <= '10-OCT-2016'));
 
CREATE TABLE SKILLS (
IMP_ID NUMBER(10) NOT NULL,
SKILL VARCHAR(15)  NOT NULL,
CONSTRAINT FK_SKILLS FOREIGN KEY (IMP_ID) REFERENCES DEVELOPERS (IMP_ID),
CONSTRAINT PK_SKILLS PRIMARY KEY (SKILL));

    
 
CREATE TABLE PROJECTS (
IMP_ID NUMBER(4) NOT NULL,
projectName VARCHAR2(10)  NOT NULL,
projectDesc VARCHAR2(10),
Q_EMP NUMBER(5),
profit NUMBER(6)  NOT NULL,
SKILL VARCHAR2(15)  NOT NULL,
CONSTRAINT FK_PROJECTS_DEV FOREIGN KEY (IMP_ID) REFERENCES DEVELOPERS (IMP_ID),
CONSTRAINT FK_SKILLS_SK FOREIGN KEY (SKILL) REFERENCES SKILLS (SKILL),
CONSTRAINT PK_PROJECTS PRIMARY KEY (projectName),
PRIMARY KEY (profit));

ALTER TABLE PROJECTS
ADD CONSTRAINT PK_PROJECTS1 PRIMARY KEY (projectName, profit);



CREATE TABLE CUSTOMERS (
custId NUMBER(4),
projectName VARCHAR2(10) NOT NULL,
profit NUMBER(6),
CONSTRAINT FK_CUSTOMERS FOREIGN KEY (projectName, profit) REFERENCES PROJECTS (projectName, profit),
CONSTRAINT PK_CUSTOMERS PRIMARY KEY (custId));
 
CREATE TABLE COMPANIES (
IT_COMP_NAME VARCHAR2(10),
projectName VARCHAR2(10) NOT NULL,
profit NUMBER(6) NOT NULL,
custId NUMBER(4) UNIQUE,
CONSTRAINT PK_COMPANIES PRIMARY KEY (IT_COMP_NAME),
CONSTRAINT FK_COMPANIES FOREIGN KEY (projectName, profit) REFERENCES PROJECTS (projectName, profit),
CONSTRAINT FR_COMPANIES_TWO FOREIGN KEY (custId) REFERENCES CUSTOMERS (custId));

ALTER TABLE DEVELOPERS
ADD salary NUMBER (7);

ALTER TABLE PROJECTS
ADD COST NUMBER (7);

INSERT ALL
INTO DEVELOPERS (IMP_ID,forname,surname,dateOfEmp,posInProject,salary)
VALUES(0001,'PETER','PETROV','12-DEC-2015','C++DEV',2000)
INTO DEVELOPERS (IMP_ID,forname,surname,dateOfEmp,posInProject,salary)
VALUES(0002,'KATE','PETROVA','15-SEP-2013','FRONT_END_DEV',2040)
INTO DEVELOPERS (IMP_ID,forname,surname,dateOfEmp,posInProject,salary)
VALUES(0003,'LARISSA','IVANOVA','09-SEP-2015','QA_MANUAL',1400)
INTO DEVELOPERS (IMP_ID,forname,surname,dateOfEmp,posInProject,salary)
VALUES(0004,'KATIA','ZAICHENKO','08-SEP-2013','QA-AUTOMATION',1600)
INTO DEVELOPERS (IMP_ID,forname,surname,dateOfEmp,posInProject,salary)
VALUES(0005,'IVAN','KUZNETSOV','12-JUN-2014','JAVA_DEV',2600)
INTO DEVELOPERS (IMP_ID,forname,surname,dateOfEmp,posInProject,salary)
VALUES(0006,'ALEX','RAZUMOVSKIY','25-DEC-2012','BA',2000)
INTO DEVELOPERS (IMP_ID,forname,surname,dateOfEmp,posInProject,salary)
VALUES(0007,'PAVEL','PETROV','08-AUG-2011','JS_DEV',3000)
SELECT 1 FROM DUAL;

INSERT ALL
INTO SKILLS (IMP_ID,SKILL)
VALUES(0001,'MANUAL_TEST')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0002,'AUTOMATION_TEST')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0003,'JS_DEV')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0004,'JAVA_DEV')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0005,'C_DEV')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0006,'DEV-OPPS')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0007,'BA')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0004,'DBA')
INTO SKILLS (IMP_ID,SKILL)
VALUES(0005,'ENGLISH')
SELECT 1 FROM DUAL;

INSERT ALL
INTO PROJECTS (IMP_ID,projectName,projectDesc,Q_EMP,profit,SKILL,costs)
VALUES(0002,'BANK2','INTEGRATION',30,30000,'MANUAL_TEST',43000)
INTO PROJECTS (IMP_ID,projectName,projectDesc,Q_EMP,profit,SKILL,costs)
VALUES(0007,'TRAVEL1','ENGLISH_TRAV',10,20000,'MANUAL_TEST',53000)
INTO PROJECTS (IMP_ID,projectName,projectDesc,Q_EMP,profit,SKILL,costs)
VALUES(0005,'TRAVEL2','SCOTISH_TRAV',15,12000,'JAVA_DEV',23000)
INTO PROJECTS (IMP_ID,projectName,projectDesc,Q_EMP,profit,SKILL,costs)
VALUES(0003,'BANK3','IRELAND',15,12000,'MANUAL_TEST',53000)
INTO PROJECTS (IMP_ID,projectName,projectDesc,Q_EMP,profit,SKILL,costs)
VALUES(0007,'BANK1','ACCOUNTING',20,20000,'MANUAL_TEST',93900)
SELECT 1 FROM DUAL;

INSERT ALL
INTO CUSTOMERS (custId,projectName,profit)
VALUES(3001,'BANK2',30000)
INTO CUSTOMERS (custId,projectName,profit)
VALUES(3002,'TRAVEL1',20000)
INTO CUSTOMERS (custId,projectName,profit)
VALUES(3003,'BANK3',12000)
SELECT 1 FROM DUAL;

INSERT ALL
INTO CUSTOMERS (custId,projectName,profit)
VALUES(3004,'BANK1',20000)
INTO CUSTOMERS (custId,projectName,profit)
VALUES(3005,'TRAVEL2',12000)
SELECT 1 FROM DUAL;

INSERT ALL 
INTO COMPANIES (IT_COMP_NAME,projectName,profit,custId)
VALUES('COMPANY_ONE','BANK2',30000,3001)
INTO COMPANIES (IT_COMP_NAME,projectName,profit,custId)
VALUES('COMPANY_TWO','BANK3',12000,3003)
INTO COMPANIES (IT_COMP_NAME,projectName,profit,custId)
VALUES('COMPANY_TWO','TRAVEL1',20000,3002)
INTO COMPANIES (IT_COMP_NAME,projectName,profit,custId)
VALUES('COMPANY_ONE','TRAVEL2',12000,3005)
INTO COMPANIES (IT_COMP_NAME,projectName,profit,custId)
VALUES('COMPANY_ONE','BANK1',20000,3004)
SELECT 1 FROM DUAL;

ALTER TABLE COMPANIES 
DROP CONSTRAINT PK_COMPANIES;